### ISSUE TITLE
identify-adapters error

### ISSUE THREAD

**Issue by helloworld44** [MikkelSchubert/adapterremoval#10]
Hi,
I used AdapterRemoval (ver. 2.1.7) to identify adapter sequences from paired-ended reads, but it returns an error message.
`AdapterRemoval --identify-adapters --file1 file_R1.fastq --file2 file_R2.fastq`
`Attemping to identify adapter sequences ...`
`Error reading FASTQ record at line 1; aborting:`
    `invalid character in FASTQ sequence; only A, C, G, T and N
    are expected!`
My fastq files have been used with other programs without problems (like FastQC or bowtie2). The quality score encoding is Sanger / Illumina 1.9.
I join here the ten first sequences from each fastq file. Could you tell me what is the problem ?
Thank you.

[file_R2.zip](https://github.com/MikkelSchubert/adapterremoval/files/410021/file_R2.zip)
[file_R1.zip](https://github.com/MikkelSchubert/adapterremoval/files/410022/file_R1.zip)

**Comment by MikkelSchubert** [comment]
Hi,
Looking at the files you attached, the problem appears to be the files use DOS / Windows style newlines (\r\n) rather than Unix style newlines (\n). Currently AdapterRemoval only handles the latter. I'll add support for both in the next release of AdapterRemoval, but in the mean time you can use the 'dos2unix' program to convert your files to the supported type of newlines:

`$ dos2unix file_R1.fastq file_R2.fastq`
`$ AdapterRemoval --file1 file_R1.fastq --file2 file_R2.fastq`
`Trimming paired end reads ...`
`Processed a total of 20 reads in 0.0s; 69,000 reads per second on average ...`

Sorry for the inconvenience.

**Comment by helloworld44** [comment]
Hi,
   Thank you for your quick reply.

**Comment by MikkelSchubert** [comment]
Support for Windows newlines (\r\n) was added in version 2.2.0, which should take care of this problem, but unfortunately I forgot to close this issue. Do not hesitate to open a new issue if you run into other problems.

Best,
 Mikkel
