### ISSUE TITLE
Is Phred encoding automatically detected?

### ISSUE THREAD

**Issue by tseemann** [MikkelSchubert/adapterremoval#3]
After reading the docs I am still bit confused as to whether you auto-detect Phred+33 or Phred+64 ?

If so, will it handle Q=42 (eg `K`) in Sanger Phred+33 files?  
Many parsers fail when Q > 40 but it can exist in Moleculo and other data.

Will things still work if R1 is Phred+33 and R2 is Phred+64 ?

**Comment by MikkelSchubert** [comment]
Phred encoding is not detected automatically (you have to use the --qualitybase option), but the program will attempt to validate your selection against input data to detect mistakes. Furthermore, by default AdapterRemoval will only accept qualities in the range 0 (or -5, for Solexa) to 41, but this maximum can be changed using the --qualitymax option.

This default maximum was chosen not only to detect malformed or misidentified input (in terms of the encoding), but also because the --collapse option often results in an increase in the quality score (when merging matching bases), which must therefore be capped at some reasonable value.

So yes, AdapterRemoval can handle data where Q > 40, but you will need to use the --qualitymax option when processing such data. I am not likely to be adding automatic quality detection, since I think this is better left to the user to determine, and because of the --collapse option.

**Comment by tseemann** [comment]
It's disappointing you will not implement auto-detection of the FASTQ encoding, as it means it can't be used for mixed data sets involving historical data from SRA. But for people that only analyse their own data then the default Q+33 will be fine. I'll stick to Trimmomatic for now.

**Comment by MikkelSchubert** [comment]
If by "mixed data sets" you simply mean multiple SRA runs with different encodings, then this is trivially handled by by specifying the quality encoding of each run when using AdapterRemoval, and setting the output to the desired encoding (typically Phred+33). This is equivalent to how Trimmomatic works.

If by mixed data sets you instead mean individual FASTQ files containing a mix of Phred+33 and Phred+64 encoded reads, then that is the very last place I would attempt to employ automatic detection of the Phred encoding.

As you are aware, the range of valid values for Phred+33 and Phred+64 is overlapping (in particular, the rage from '@' to 'I' for Phred+64 encoded quality scores, and ';' to 'I' for Solexa encoded quality scores, assuming a maximum score of 41 for Phred+33), meaning that a set of high quality Phred+33 encoded scores may fall entirely within the range of valid, low quality Phred+64 or Solexa encoded quality scores, and vice versa. Therefore, to prevent overestimating the quality of such reads, you would either have to systematically assume that these values signified low qualities, or you would to have exclude these reads outright. 

Such ad hoc solutions to dealing with mismanaged data is, in my opinion, best left in the hands of the persons attempting to make use of said data, and either of the solutions mentioned above could be implemented easily in a small script.
