### ISSUE TITLE
AdapterRemoval doesn't work with paired end reads >1GB

### ISSUE THREAD

**Issue by Giorgia94** [MikkelSchubert/adapterremoval#37]
Hi. I'm working on aDNA and I have launched AdapterRemoval on raw reads (paired end reads).

This is the tipe of pipeline I used:
nohup directory/adapterremoval-2.2.4/build/AdapterRemoval --threads 8 --identify-adapters --file1 namefile1_r1.txt.gz --file2 namefile2_r2.txt.gz &

I does work with file <1GB, but I noticed that it stops running with files >1GB without error messages. Does anyone know why? Is it really a problem related to file dimension? It seems weird to me.

Thanks

**Comment by MikkelSchubert** [comment]
Hi,

There shouldn't be limitations on the input file sizes and I have regularly
used AdapterRemoval on files that were tens of GB in size.

AdapterRemoval should print error messages on failures barring a SIGSEV or
being forcibly terminated by the OS, so you can try checking dmesg or
running it in the foreground instead of using nohup (use screen or tmux if
you need to disconnect while it is running).

Cheers,
 Mikkel

**Comment by Giorgia94** [comment]
Thank you so much for your help!
It works.

Giorgia
