### ISSUE TITLE
Incorrect trimming of adapters when alignment contains gaps

### ISSUE THREAD

**Issue by sc13-bioinf** [MikkelSchubert/adapterremoval#40]
All alignments were processed with the following parameters:
<pre>AdapterRemoval --file1 test.fastq --basename out.fastq --gzip --threads 4 --trimns --trimqualities --preserve5p --adapter1 AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC --adapter2 AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTA --minlength 30 --minquality 20 --minadapteroverlap 1</pre>

The reads afterwards are taken from the discards file and appear to be shorter than they should be by the gap length. It is an unknown if the gaps in the alignment of the adapter make discarding these reads beneficial, but perhaps that should be an explicit option and choice for the user. The following alignments illustrate the problem:

One:

<pre>

@K00233:58:HJGVTBBXX:5:2121:29680:48526 1:N:0:ATGGTATA+CATATTGA
CGGCGCCTCGGGCTTCGGCAACTTCGGCGGAGATCGGAAGAGACACGTCTGAACTCCAGTCACATGGTATATCTCG
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJ

CGGCGCCTCGGGCTTCGGCAACTTCGGCGGAGATCGGAAGAG-ACACGTCTGAACTCCAGTCACATGGTATATCTCG
                              ||||||||||||||||||||||||||||||||||
------------------------------AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC-------------

@K00233:58:HJGVTBBXX:5:2121:29680:48526 1:N:0:ATGGTATA+CATATTGA
CGGCGCCTCGGGCTTCGGCAACTTCGGCG
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJ

Two:

@K00233:58:HJGVTBBXX:6:1125:23581:11548 1:N:0:ATGGTATA+CATATTGA
GGCCTACCGCGCGCCGTTTCCGACGTTCAGCAGATCGGAAGCACACGTCTGAACTCCAGTCACATGGTATATCTCG
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ-FJJJ

GGCCTACCGCGCGCCGTTTCCGACGTTCAGCAGATCGGAAG--CACACGTCTGAACTCCAGTCACATGGTATATCTCG
                               ||||||||||||||||||||||||||||||||||
-------------------------------AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC-------------

@K00233:58:HJGVTBBXX:6:1125:23581:11548 1:N:0:ATGGTATA+CATATTGA
GGCCTACCGCGCGCCGTTTCCGACGTTCA
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJ

Three:

@K00233:58:HJGVTBBXX:5:2109:30036:5112 1:N:0:ATGGTATA+CATATTGA
GCGCCAGGGCCGGTGGTGGGCTCAGTGGTGAGATCGGAAGACACGTCTGAACTCCAGTCACATGGTATATCTCGTA
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ

GCGCCAGGGCCGGTGGTGGGCTCAGTGGTGAGATCGGAAGA---CACGTCTGAACTCCAGTCACATGGTATATCTCGTA
                              ||||||||||||||||||||||||||||||||||
------------------------------AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC---------------

@K00233:58:HJGVTBBXX:5:2109:30036:5112 1:N:0:ATGGTATA+CATATTGA
GCGCCAGGGCCGGTGGTGGGCTCAGTG
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJ
</pre>

In all cases the reads are discarded as the length of the gap is also trimmed from the read.

**Comment by MikkelSchubert** [comment]
Thank you for the bug-report!

I will have to review the specific examples in more detail, but I suspect
that this is simply due to AdapterRemoval performing a ungapped alignments,
where an optimal alignment will look like this:

GCGCCAGGGCCGGTGGTGGGCTCAGTGGTGAGATCGGAAGACACGTCTGAACTCCAGTCACATGGTATATCTCGTA
                                    ||  |||||||||||||||||||||
---------------------------AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC---------------

This results in the trimmed read that you observed:

GCGCCAGGGCCGGTGGTGGGCTCAGTG

The max error rate for reads is intentionally left high, under the
assumption that it is preferable to trim a little too much, as opposed to
retaining adapter sequences in your data. However, as you can see, these
properties can sometimes lead to slightly unexpected results.

The type of alignment used in the original version of AdapterRemoval
(Lindgreen 2012) based on the observation that indels are rare in Illumina
data, and is retained in AdapterRemoval v2 as it was designed to be a
drop-in replacement for the original software.

Best regards,
 Mikkel

**Comment by MikkelSchubert** [comment]
Thank you once again for the report.

I have looked through the examples you've provided, and as far as I can determine they are all the by-product of AdapterRemoval performing a gap-less alignment. So while the trimming of these particular reads is not optimal, it is not a bug in the program as such, but is rather a limitation of the alignment algorithm, and not something that can be avoided without adding an entirely new alignment algorithm to AdapterRemoval.

Best regards,
 Mikkel
