### ISSUE TITLE
stdout and stderr reversed?

### ISSUE THREAD

**Issue by UdoGi** [MikkelSchubert/adapterremoval#46]
I have piped the output of AdapterRemoval to two separate log files for stdout and stderr using the > and 2> operator and noticed that the stdout output is found in stderr.  

So running for example `AdapterRemoval --file1 myreads_1.fastq.gz --file2 myreads_2.fastq.gz 1> stdout.log 2> stderr.log` will result in an empty stdout.log and the stderr.log file containing the report on which files it reads and how long it took (which I believe should be in stdout)

**Comment by MikkelSchubert** [comment]
AdapterRemoval intentionally does not output diagnostic messages to STDOUT. This makes it possible to pipe trimmed reads to another program by using /dev/stdout as the output file, something that is mainly useful with the `--combined-output` option along with the `--interleaved-output` option for PE reads.

It also makes it easier to pipe the summary report from the `--identify-adapters` sub-command to a file, since only the report itself is written to STDOUT.
