### ISSUE TITLE
How to demultiplexing paired-end reads in mixed orientation?

### ISSUE THREAD

**Issue by rexhancx** [MikkelSchubert/adapterremoval#56]
Dear Dr. Schubert,

this tool has helped me a lot, thanks a lot.

for my protocol, the barcodes location is depending on the orientation in which the DNA was sequenced.

for example, the read layout could be either this

r1:barcode1-forwardprimer-sequence; r2: barcode2-reverseprimer-sequence

or this

r1: barcode2-reverseprimer-sequence; r2: barcode1-forwardprimer-sequence.

so how to demultiplexing paired-end reads in mixed orientation in a single run?  

if there's no such function, could you consider adding this function in later version?

wish everything goes well with you. :)

**Comment by MikkelSchubert** [comment]
Dear Rex Han,

If I understand you correctly, then I am afraid that AdapterRemoval cannot handle your data.

You write that your reads look like this [1]:

    a. r1: barcode1-forwardprimer-sequence
       r2: barcode2-reverseprimer-sequence
    b. r1: barcode2-reverseprimer-sequence
       r2: barcode1-forwardprimer-sequence

However, AdapterRemoval expects the following [2]:

    a. r1: barcode1-sequence-forwardprimer
       r2: barcode2-sequence-reverseprimer
    b. r1: barcode2-sequence-reverseprimer
       r2: barcode1-sequence-forwardprimer

That is to say that reads must start with a barcode, then the sequence, and finally end with an adapter. If your data does not look like that, then you cannot use AdapterRemoval and it is unlikely that support for the kind of layout you describe will be added.

However, if your data actually matches what AdapterRemoval requires [2], then you can perform the trimming and demultiplexing as follows:

Firstly, you will need to specify two sets of barcodes for each sample:

    $ cat my_barcodes.txt
    Sample1a	barcode1	barcode2
    Sample1b	barcode2	barcode1

And secondly, you will need to specify two sets of adapters for use with --adapter-list:

	$ cat my_adapters.txt
	forwardprimer	reverseprimer
	reverseprimer	forwardprimer

Once you have done that, then you can run with those lists AdapterRemoval as follows (adding your own input/output/trimming/etc options):

	$ AdapterRemoval --adapter-list my_adapters.txt --barcode-list my_barcodes.txt ...

You will get two sets of output files per sample (e.g. Sample1a and Sample1b), but it's pretty simple to combine those afterwards. Note also that this *will* run slower than regular demultiplexing, since AdapterRemoval will try both sets of adapters for each read, regardless of the barcode.

Best,
 Mikkel

**Comment by rexhancx** [comment]
Dear Dr. Schubert,

Glad to hear from you.

Thanks, I'll try this `--adapter-list`.

wish everything goes well with u.
