### ISSUE TITLE
remove adapters sequences from BGI/MGI platform

### ISSUE THREAD

**Issue by binlu1981** [MikkelSchubert/adapterremoval#59]
Hi Mikkel,

Dose the Adapterremoval can identify and remove adapters in single/pair-end data from BGI/MGI platform (T7 et. al)?  Or should I feed adapters information to it?

MGI sequencing adapter left = “AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA”
MGI sequencing adapter right = “AAGTCGGATCGTAGCCATGTCGTTCTGTGAGCCAAGGAGTTG”

Or could these 2 (or maybe all listed) adapter sequences be added to the set of built-in?

Thanks
Bin

**Comment by MikkelSchubert** [comment]
Hi Bin,

You need to specify these adapter sequences yourself using the `--adapter1` and `--adapter2` options.

If you don't know the adapter sequence, then AdapterRemoval can help identify adapters sequences in PE data using the `--identify-adapters` option, which prints a consensus sequence. But in my experience this is not reliable without human review to verify adapter sequences, which is why it is a separate tool and not done automatically.

There is more information in the manual:
https://adapterremoval.readthedocs.io/en/stable/getting_started.html#a-note-on-specifying-adapters

Best,
Mikkel
