### ISSUE TITLE
Can you remove large number of probe sequences from just one end?

### ISSUE THREAD

**Issue by delavefm** [MikkelSchubert/adapterremoval#6]
I am working with a targeted resequencing approach that uses probes to capture targets. These probe sequences range from ~20-40bp and are located after the RD1 sequencing primer from Illumina. The list can be very large (e.g. 15K), bit can be provided in a file. The adaptor on the other end is universal. Can adaptremoval go though a list of ;aired adaptors where one is each probe and the second is constant in reasonable time?

Thanks!

**Comment by MikkelSchubert** [comment]
While AdapterRemoval can handle multiple paired adapter sequences, such as what you describe, performance scales roughly linearly with the number of sequences, and you would probably not see an acceptable performance when using such a large number of different adapters. I believe that AlienTrimmer (Criscuolo 2013) may be a better solution, in your case, since that program scales very well with the number of different adapter sequences:
http://www.sciencedirect.com/science/article/pii/S0888754313001481

Cheers
