### ISSUE TITLE
How to interpret the outputs of the multiple inputs after trimming?

### ISSUE THREAD

**Issue by hyjforesight** [MikkelSchubert/adapterremoval#61]
Hello AdapterRemoval,
Thanks for developing this amazing package!

I have 4 fastq files. WT_1 and WT_2 are paried-end sequencing files from sample WT. KO_1 and KO_2 are paried-end sequencing files from sample KO.
WT_1.fastq.gz
WT_2.fastq.gz
KO_1.fastq.gz
KO_2.fastq.gz

I run `AdapterRemoval --file1 WT_1.fastq.gz KO_1.fastq.gz --file2 WT_2.fastq.gz KO_2.fastq.gz --adapter1 CTGTCTCTTATACACATCT --adapter2 CTGTCTCTTATACACATCT --thread 16`, and only get 2 files: `your_output.pair1.truncated` and `your_output.pair1.truncated`. Is `your_output.pair1.truncated` a merged file that combines WT_1 and KO_1 after trimming? If so, it doesn't make any sense to combine mate1s of two different samples.

Shall I only input the fastq files from the same experiment group into this run? I mean, if I have
WT1_1.fastq.gz
WT1_2.fastq.gz
WT2_1.fastq.gz
WT2_2.fastq.gz
KO1_1.fastq.gz
KO1_2.fastq.gz
KO2_1.fastq.gz
KO2_2.fastq.gz
I should do trimming for WT and KO respectively, like `AdapterRemoval --file1 WT1_1.fastq.gz WT2_1.fastq.gz --file2 WT1_2.fastq.gz WT2_2.fastq.gz --adapter1 CTGTCTCTTATACACATCT --adapter2 CTGTCTCTTATACACATCT --thread 16` first?

Could you please explain a little more about the meaning of pair1 and pair2 files when we input multiple inputs into this run?
Thanks!
Best
YJ

**Comment by MikkelSchubert** [comment]
Dear YJ,

If you specify multiple input files for AdapterRemoval, then it essentially treats them as one big file (or two big files in paired mode). So if you specify FASTQ files from multiple samples then the output will also contain a mix of those samples. This is useful if you have multiple files for the same sample, but only in that case.

In other words, you are right that you should trim the WT sample and the KO sample using two separate commands:

    AdapterRemoval --file1 WT1_1.fastq.gz WT2_1.fastq.gz --file2 WT1_2.fastq.gz WT2_2.fastq.gz --adapter1 CTGTCTCTTATACACATCT --adapter2 CTGTCTCTTATACACATCT --thread 16
    AdapterRemoval --file1 KO1_1.fastq.gz KO2_1.fastq.gz --file2 KO1_2.fastq.gz KO2_2.fastq.gz --adapter1 CTGTCTCTTATACACATCT --adapter2 CTGTCTCTTATACACATCT --thread 16

I'd also recommend using the `--basename` command-line option to give the output files distinct names instead of `your_output.*`, to avoid overwriting files by accident:

    AdapterRemoval --basename output_WT --file1 WT1_1.fastq.gz WT2_1.fastq.gz --file2 WT1_2.fastq.gz WT2_2.fastq.gz --adapter1 CTGTCTCTTATACACATCT --adapter2 CTGTCTCTTATACACATCT --thread 16
    AdapterRemoval --basename output_KO --file1 KO1_1.fastq.gz KO2_1.fastq.gz --file2 KO1_2.fastq.gz KO2_2.fastq.gz --adapter1 CTGTCTCTTATACACATCT --adapter2 CTGTCTCTTATACACATCT --thread 16

Cheers,
Mikkel

**Comment by hyjforesight** [comment]
Dear Mikkel,
Thanks for the response!
> This is useful if you have multiple files for the same sample, but only in that case.
Is it correct to do the multiple inputs if we have the duplicates for the same experiment group? I mean, WT1 and WT2 are from the same WT experiment group, but they're from different mice. So, we should not recognize them as the **same sample**? Shall also do trimming for WT1 and WT2 respectively?
Thanks!
Best,
YJ

**Comment by MikkelSchubert** [comment]
That is correct. If they are different samples/individuals, then you should process them individually. Otherwise you won't be able to separate them in downstream analyses. The ability to process multiple files at once is really only meant for the case where you have multiple FASTQ files for the same exact sample, for example if your files were split at some point. 

Best,
Mikkel

**Comment by hyjforesight** [comment]
Hello @MikkelSchubert 
Thanks for the clear explanation. We'll cite your paper once we publish our data!
